apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage
  namespace: cima-registry
  labels:
    app: registry
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 20Gi
