#!/bin/bash
kubectl create secret generic elasticsearch-cert --from-file elasticsearch/tls/elasticsearch-certificates.p12 -n cima-logging
kubectl create secret generic elasticsearch-keystore --from-file elasticsearch/keystore/elasticsearch.keystore -n cima-logging
kubectl create secret generic kibana-keystore --from-file kibana/keystore/kibana.keystore -n cima-logging
kubectl apply -f elasticsearch/
kubectl apply -f kibana/
kubectl apply -f fluentd/
