#!/bin/bash
mvn -f ../cima-comun/pom.xml clean install
mvn clean package

#comprobamos si existe proxy en donde se este construyendo la imagen
#NOTA: verificar si cambia la definicion "http proxy" con la version de docker que se este utilizando
#En dado caso, ajustar el parametro.
CHECK_PROXY="$(docker info | grep -i 'http proxy')"
if [ "$CHECK_PROXY" ]; then
	DOCKER_PROXY=$(echo $CHECK_PROXY | awk -F': ' '{print $NF}')
	docker build --build-arg http_proxy=$DOCKER_PROXY -f src/main/docker/oc/Dockerfile -t docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-dev/cima-mspocws .
else 
	docker build -f src/main/docker/oc/Dockerfile -t docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-dev/cima-mspocws .
fi

docker push docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-dev/cima-mspocws

#verificamos que la aplicacion ya exista para que no la parche al primer despliegue
EXISTS=false
if kubectl get deployments -n=cima-dev | grep -q cima-mspocws-app; then
	 EXISTS=true
fi
kubectl apply -f src/main/docker/oc/kubernetes/

#si existe la aplicacion la parcha y se actualiza
if [ "$EXISTS" == true ]; then
	 kubectl patch deployment cima-mspocws-app -p '{"spec":{"template":{"metadata":{"labels": { "buildate" : "'$(date '+%d-%m-%Y_%H.%M.%S.%3N')'", "version" : "latest"}}}}}' -n=cima-dev
fi

docker rmi $(docker images -aq -f dangling=true)