server:
    port: 9080

logging:
  level:
    root: INFO
    
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: ["configprops", "env", "health", "info", "threaddump", "logfile", "metrics", "beans", "prometheus"]
      path-mapping:
        prometheus: /metrics
        metrics: /management/metrics
        configprops: /management/configprops
        env: /management/env
        health: /management/health
        info: /management/info
        threaddump: /management/threaddump
        logfile: /management/logfile
        beans: /management/beans
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

opentracing:
  jaeger:
    udp-sender:
      host: ${jaeger.agent.host:localhost}
    enable-b3-propagation: true
  spring:
    web:
      skip-pattern: /api-docs.*|/swagger.*|.*\.png|.*\.css|.*\.js|.*\.html|/favicon.ico|/hystrix.stream|/metrics.*|/management.*|/soap-api
      
cors:
  config:
    cors:
      allowed-origins:
      - http://localhost:3000
      max-age: 3600
      allowed-methods: "*"