apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
  namespace: cima-logging
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  ports:
  - port: 9300
    name: inter-node
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: cima-logging
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    name: rest
  selector:
    app: elasticsearch
