apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: cima-logging
spec:
  serviceName: elasticsearch-cluster
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
      - name: elastic-cert
        secret:
          secretName: elastic-cert
      - name: elastic-config
        configMap:
          name: elastic-config
      containers:
      - name: elasticsearch
        image: image-registry.openshift-image-registry.svc:5000/cima-logging/elasticsearch-7.5.1
        resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        - name: elastic-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
        - name: elastic-cert
          mountPath: /usr/share/elasticsearch/config/certs
        env:
          - name: CLUSTER_NAME
            value: es-cluster
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_LIST
            value: "elasticsearch-0.elasticsearch-cluster.cima-logging,elasticsearch-1.elasticsearch-cluster.cima-logging"
          - name: MASTER_NODES
            value: "elasticsearch-0,elasticsearch-1"
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
          - name: ELASTIC_PASSWORD
            value: "cimadmin123"
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      initContainers:
      - name: increase-vm-max-map
        image: image-registry.openshift-image-registry.svc:5000/cima-logging/busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fix-permissions
        image: image-registry.openshift-image-registry.svc:5000/cima-logging/busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: es-data
      labels:
        app: elasticsearch
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: nas1200
      resources:
        requests:
          storage: 10Gi
