kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: cima-networking
  labels:
    app: traefik-ingress-controller
spec:
  selector:
    matchLabels:
      app: traefik-ingress-controller
  template:
    metadata:
      labels:
        app: traefik-ingress-controller
        name: traefik-ingress-controller
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: traefik-tls-cert
        secret:
          secretName: traefik-tls-cert
      - name: traefik-dynamic-configmap
        configMap:
          name: traefik-dynamic-configmap
      containers:
      - image: traefik
        name: traefik-ingress-controller
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /ssl
          name: traefik-tls-cert
        - mountPath: /traefik/traefik.toml
          name: traefik-dynamic-configmap
          subPath: traefik.toml
        args:
        - --global.checknewversion=false
        - --global.sendanonymoususage=false
        - --entrypoints.websecure.address=:443
        - --entryPoints.websecure.http.tls
        - --providers.kubernetesingress
        - --log.level=INFO
        - --api.dashboard
        - --metrics.prometheus=true
        - --metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000
        - --metrics.prometheus.entryPoint=traefik
        - --providers.file.filename=/traefik/traefik.toml
        ports:
        - name: websecure
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
        securityContext:
          capabilities:
              drop:
              - ALL
              add:
              - NET_BIND_SERVICE
          # tiene que ejecutar como root
          # si se enlazan los puertos 80 y 443
          # respectivamente
          # runAsUser: 65532
          # runAsGroup: 65532
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-service
  namespace: cima-networking
spec:
  selector:
    app: traefik-ingress-controller
  ports:
  - port: 443
    name: websecure
  - port: 8080
    name: admin
