kind: ConfigMap
apiVersion: v1
metadata:
  name: kibana-config
  namespace: cima-logging
  labels:
    name: kibana-config
data:
  kibana.yml: |
    # Default Kibana configuration for docker target
    server:
      name: "kibana"
      host: "0.0.0.0"
      publicBaseUrl: "http://0.0.0.0:5601"
    elasticsearch:
      hosts: [ "http://elasticsearch.cima-logging:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true
    xpack:
      reporting:
        kibanaServer:
          hostname: localhost
        roles:
          enabled: false
