apiVersion: apps/v1
kind: Deployment
metadata:
  name: cima-mspocws-app
  namespace: cima-dev
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: cima-mspocws-app
  template:
    metadata:
      labels:
        fluentd-log-format: "spring-boot"
        app: cima-mspocws-app
      annotations:
        prometheus.io.scrape: "true"
    spec:
      containers:
      - name: cima-mspocws-app
        image: registry.cima.es:30443/cima-mspocws
        imagePullPolicy: Always
        env:
        - name: SPRING_MAIN_BANNER-MODE
          value: "off"
        - name: SPRING_PROFILES_ACTIVE
          value: kibana
        - name: JAVA_OPTS
          value: " -Xms256m -Xmx512m 
          -XX:MaxMetaspaceSize=128m 
          -XX:TieredStopAtLevel=1 
          -XX:+UnlockExperimentalVMOptions 
          -XX:+UseCGroupMemoryLimitForHeap"
        - name: JAEGER_AGENT_HOST
          # DESARROLLO all-in-one
          # value "jaeger-agent.cima-tracing"
          # PRODUCCION
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - name: http
          containerPort: 9080
        readinessProbe:
          httpGet:
            path: /management/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /management/health
            port: http
          initialDelaySeconds: 200
