apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: cima-tracing
  annotations:
      kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - jaeger.cima.es
  rules:
    - host: jaeger.cima.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
