apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-local-provisioner
  namespace: cima-nfs
  labels:
    app: nfs-server
spec:
  storageClassName: local-storage
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 100Gi
