apiVersion: v1
kind: Namespace
metadata:
  name: openshift-console
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-monitoring
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-apps
