apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jcr-storage
  namespace: cima-jcr
  labels:
    app: cima-jfrog-jcr
spec:
  storageClassName: nas1200
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 20Gi
