apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: cima-monitoring
  labels:
    app: grafana
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 5Gi
