kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana
  namespace: cima-monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
            requests: 
              memory: 1Gi
              cpu: 500m
          volumeMounts:
            - name: storage
              mountPath: /var/lib/grafana
      securityContext:
        fsGroup: 472
        runAsUser: 472
      initContainers:
      - name: grafana-storage-permission-fix
        image: busybox
        command:
        - sh
        - -c
        - chown -R 472:472 /var/lib/grafana
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: grafana-storage
