apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: cima-monitoring
  labels:
    app: grafana
spec:
  storageClassName: grafana
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
