apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-all.yaml
  - wazuh-manager-policy.yaml
  - wazuh-indexer-policy.yaml
  - wazuh-dashboard-policy.yaml
  - wazuh-securityadmin-policy.yaml
  - wazuh-agent-policy.yaml
