apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-agent
  namespace: security
  labels:
    app: wazuh-agent
    app.kubernetes.io/name: wazuh-agent
    app.kubernetes.io/component: security
    app.kubernetes.io/version: "4.14.4"
