#!/bin/bash
kubectl apply -f namespace.yml
kubectl create secret tls traefik-tls-cert --key traefik/tls/tls.key --cert traefik/tls/tls.crt -n cima-networking
kubectl create secret generic elastic-cert --from-file elasticsearch/tls/elastic-certificates.p12 -n cima-logging
kubectl apply -f volumes/
kubectl apply -f traefik/
kubectl apply -f elasticsearch/
kubectl apply -f kibana/
kubectl apply -f fluentd/
kubectl apply -f prometheus/
kubectl apply -f grafana/
kubectl apply -f jaeger/
kubectl apply -f dashboard/
