#!/bin/bash
./createdir
kubectl apply -f namespace.yml
kubectl create secret tls traefik-tls-cert --key traefik/tls/tls.key --cert traefik/tls/tls.crt -n cima-networking
kubectl create secret generic elastic-cert --from-file elasticsearch/tls/elastic-certificates.p12 -n cima-logging
kubectl create secret generic jcr-secret --from-file=.dockerconfigjson=jcr/conf/config.json  --type=kubernetes.io/dockerconfigjson -n cima-dev
kubectl create secret generic jcr-secret --from-file=.dockerconfigjson=jcr/conf/config.json  --type=kubernetes.io/dockerconfigjson -n cima-test
kubectl apply -f volumes/
kubectl apply -f nfs/
kubectl apply -f provisioner/
kubectl apply -f registry/
kubectl apply -f jcr/
kubectl apply -f traefik/
kubectl apply -f elasticsearch/
kubectl apply -f kibana/
kubectl apply -f fluentd/
kubectl apply -f prometheus/
kubectl apply -f grafana/
kubectl apply -f jaeger/
kubectl apply -f dashboard/
