#!/bin/bash
docker pull busybox
docker pull fluent/fluentd-kubernetes-daemonset:v1.7.4-debian-elasticsearch7-2.2
docker pull docker.elastic.co/elasticsearch/elasticsearch:7.5.1
docker pull docker.elastic.co/kibana/kibana:7.5.1
docker pull jaegertracing/all-in-one
docker tag fluent/fluentd-kubernetes-daemonset:v1.7.4-debian-elasticsearch7-2.2 docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-logging/fluentd-k8s-1.7.4-deb-es7-2.2
docker tag docker.elastic.co/elasticsearch/elasticsearch:7.5.1 docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-logging/elasticsearch-7.5.1
docker tag docker.elastic.co/kibana/kibana:7.5.1 docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-logging/kibana-7.5.1
docker tag busybox docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-logging/busybox
docker tag jaegertracing/all-in-one docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-tracing/jaeger-all-in-one
docker push docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-logging/fluentd-k8s-1.7.4-deb-es7-2.2
docker push docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-logging/elasticsearch-7.5.1
docker push docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-logging/kibana-7.5.1
docker push docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-logging/busybox
docker push docker-registry-openshift-image-registry.apps.tirea-pre.cloudgarden.telefonica.com/cima-tracing/jaeger-all-in-one


