#!/bin/bash
kubectl delete namespace cima-dev
kubectl delete namespace cima-test
kubectl delete namespace cima-logging
kubectl delete namespace cima-networking
kubectl delete namespace cima-monitoring
kubectl delete namespace cima-tracing
kubectl delete namespace kubernetes-dashboard
kubectl get pv | grep Released | awk '{print $1}' | xargs kubectl delete pv
kubectl delete clusterrole fluentd
kubectl delete clusterrolebinding fluentd
kubectl delete clusterrole traefik-ingress-controller
kubectl delete clusterrolebinding traefik-ingress-controller
kubectl delete clusterrole prometheus
kubectl delete clusterrolebinding prometheus
kubectl delete clusterrole prometheus
kubectl delete clusterrolebinding prometheus
kubectl delete clusterrole kubernetes-dashboard
kubectl delete clusterrolebinding kubernetes-dashboard

